[toolchain]

[features]
seeds = false
skip-lint = false
[programs.localnet]
w3balance_contract = "46gecgivx6mbKb7gfZFVjBGbBgR1n91NEj3naj2LrF8u"
raydium_cp_swap = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# cp-swap program in mainnet
[[test.validator.clone]]
address = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"

# cp-swap create_pool_fee_reveiver in mainnet
[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

# cp-swap ammConfig in mainnet
[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"

# cp-swap lookup table
[[test.validator.clone]]
address = "2immgwYNHBbyVQKVGCEkgWpi53bLwWNRMB5G2nbgYV17"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zacharyroberts/wallets/poker-dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
