[toolchain]

[features]
seeds = false
skip-lint = false
[programs.localnet]
w3balance_contract = "46gecgivx6mbKb7gfZFVjBGbBgR1n91NEj3naj2LrF8u"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zacharyroberts/wallets/poker-dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
